### ISSUE TITLE
Complete a tutorial for Recommender Systems

### ISSUE THREAD

**Issue by bbaruque** [jaswellnitz/tourist-chatbot#30]
Using:
Mahout - https://mahout.apache.org/users/recommender/userbased-5-minutes.html
Spark MLlib - https://spark.apache.org/docs/latest/mllib-collaborative-filtering.html
LibRec - http://www.librec.net/

**Comment by jaswellnitz** [comment]
Apache Mahout is chosen as a machine learning library in order to build the application’s recommender. The following two tutorials were completed: Mahout Item Recommender Tutorial using Java and Eclipse as well as Creating a User-Based Recommender in 5 minutes. In order to do so, Mahout was downloaded and integrated as a library into an eclipse project. The setup was simple and the examples easy to understand. 
The following article sums up and compares the user-based and item-based recommender applications in Mahout: http://blog.chapagain.com.np/recommender-system-using-java-apache-mahout/

Alternatives:
LibRec is Java library for recommender systems that provides several state-of-the-art recommendation algorithms. However, the library is mainly used for academic purposes and has abandoned its tutorial (http://librec.net/tutorial.html not accessible).
